### PR TITLE
fix: voice message loading state

### LINKED ISSUE #1194: Issue: Chat – iOS keeps showing the loading state even after the voice message is completed.
https://github.com/user-attachments/assets/7e1c08fa-e730-486f-9d5e-763c858b58a8

### PR DESCRIPTION
**Pull request by yousef-osama11**
https://github.com/user-attachments/assets/0b6bbb3f-cb5e-4a70-ac72-8d17208a4a1a

### CODE REVIEW

**Review by AdelTamer35 — APPROVED** [review]
Good Job👏

File: core_chat_presentation/src/commonMain/kotlin/net/thechance/mena/core_chat/presentation/screen/chat/ChatViewModel.kt [hunk 1]
```diff
@@ -764,9 +764,13 @@ class ChatViewModel(
 
         val remainingMs = totalDuration - currentPosition
         val isNearEnd = currentPosition >= totalDuration * AUDIO_END_THRESHOLD_RATIO
+
+        val wasNearEnd = lastPosition >= totalDuration * AUDIO_END_THRESHOLD_RATIO
+        val positionReset = currentPosition == 0L && wasNearEnd
```
Comment (yousef-osama11) [inline core_chat_presentation/src/commonMain/kotlin/net/thechance/mena/core_chat/presentation/screen/chat/ChatViewModel.kt:769]: we need to check last position not current position so we need `wasNearEnd`

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by Radwa85 — APPROVED** [review]
