### PR TITLE
fix/DKN-246-search-screen-should-display-no-internet-connection-content

### LINKED ISSUE #1143: Issue: Dukan – When searching, the “No Results” state is displayed even when an error occurs.
https://github.com/user-attachments/assets/6f8e0449-9fad-4018-befd-ef51d4c6b830

### PR DESCRIPTION
**Pull request by mostafa-n3ma**
showing no internet content and hiding the search bar when no connection found

### CODE REVIEW

**Review by haideraljawasim — APPROVED** [review]

File: dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/viewModel/search/SearchViewModel.kt [hunk 1]
```diff
@@ -224,12 +225,17 @@ class SearchViewModel(
...
 
     private fun handleNoInternetException() {
+//        updateState {
+//            copy(
+//                snackBarUiState = SnackBarUiState(
+//                    message = Res.string.no_internet_message,
+//                    snackBarType = SnackBarType.ERROR
+//                )
+//            )
+//        }
```
Comment (YoussefmSaber) [inline dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/viewModel/search/SearchViewModel.kt]: delete dead code

File: dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/screen/search/SearchScreen.kt [hunk 2]
```diff
@@ -105,12 +116,17 @@ private fun SearchContent(
...
-                        body = stringResource(resource = Res.string.no_result_found_body)
-                    )
+                SearchUiState.SearchContentState.NoInternet -> {
+                    Box (
+                        modifier = Modifier.fillMaxSize(),
+                        contentAlignment = Alignment.Center
+                    ){
+                        NoInternetContent(
+                            onRetry = {listener.onSearchChanged(state.searchQuery)},
+                            isLoading = false
```
Comment (ahmedNaser7) [inline dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/screen/search/SearchScreen.kt:126]: What if user search about something but it not found , we need to disply no result content , add this content again but inside  `NoResult` state

Comment (mostafa-n3ma) [reply dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/screen/search/SearchScreen.kt:126]: The list would be empty and it is applied somewhere else this was dead code 💀 not used

Comment (mostafa-n3ma) [reply dukan_presentation/src/commonMain/kotlin/net/thechance/mena/dukan/presentation/screen/search/SearchScreen.kt:126]: The empty content is called from the lazy list when the list is empty

**Review by YoussefmSaber — APPROVED** [review]

**Review by ahmedNaser7 — APPROVED** [review]

**Review by NadaMansour20 — APPROVED** [review]
